In [1]:
import numpy as np
A = np.array([1,2,3,4])
print(A)
print(np.ndim(A))
print(A.shape)
print(A.shape[0])

[1 2 3 4]
1
(4,)
4


In [2]:
B = np.array([[1,2], [3,4], [5,6]])
print(B)
print(np.ndim(B))
print(B.shape)

[[1 2]
 [3 4]
 [5 6]]
2
(3, 2)


In [4]:
A = np.array([[1, 2], [3, 4]])
print(A.shape)
B = np.array([[5, 6], [7, 8]])
print(B.shape)
print('행렬곱: ')
print(np.dot(A, B))

(2, 2)
(2, 2)
행렬곱: 
[[19 22]
 [43 50]]


In [5]:
A = np.array([[1, 2, 3], [4, 5, 6]])
print(A.shape)
B = np.array([[1, 2], [3, 4], [5, 6]])
print(B.shape)
print('행렬곱: ')
print(np.dot(A, B))

(2, 3)
(3, 2)
행렬곱: 
[[22 28]
 [49 64]]


In [6]:
#행렬곱을 하려면 행과 열의 원소 수가 같아야 함
C = np.array([[1, 2], [3, 4]])
print(C.shape)
print(A.shape)
print(np.dot(A, C))

(2, 2)
(2, 3)


ValueError: shapes (2,3) and (2,2) not aligned: 3 (dim 1) != 2 (dim 0)

In [8]:
test1 = np.array([[1, 2], [3, 4], [5, 6]])
test2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(test1.shape)
print(test2.shape)
print(np.dot(test1, test2))

(3, 2)
(2, 4)
[[11 14 17 20]
 [23 30 37 44]
 [35 46 57 68]]


In [10]:
#대응하는 차원의 원소 수를 일치시켜야 함
A = np.array([[1, 2], [3, 4], [5, 6]])
print(A.shape)
B = np.array([7, 8])
print(B.shape)
print(np.dot(A, B))

(3, 2)
(2,)
[23 53 83]


In [11]:
#신경망에서의 행렬곱
X = np.array([1, 2])
print(X.shape)
W = np.array([[1, 3, 5], [2, 4, 6]])
print(W.shape)
Y = np.dot(X, W)
print(Y)

(2,)
(2, 3)
[ 5 11 17]


표기법

![image.png](./image/notation.png)