In [1]:
import numpy as np

In [6]:
x = np.array([1.0, 2.0, 3.0])
print(x)
print(type(x))

[1. 2. 3.]
<class 'numpy.ndarray'>


In [7]:
x = np.array([1.0, 2.0, 3.0])
y = np.array([2.0, 4.0, 6.0])

#원소별로 각각 계산
print(x + y)
print(x - y)
print(x * y)
print(x / y)

[3. 6. 9.]
[-1. -2. -3.]
[ 2.  8. 18.]
[0.5 0.5 0.5]


In [8]:
x = np.array([1.0, 2.0, 3.0])
print(x / 2.0)

[0.5 1.  1.5]


In [19]:
#2차원 배열
A = np.array([[1, 2,], [3, 4]])
print('A:\n',A)
print('행렬의 형상:', A.shape)
print('행렬에 담긴 원소의 자료형:', A.dtype)

A:
 [[1 2]
 [3 4]]
행렬의 형상: (2, 2)
행렬에 담긴 원소의 자료형: int64


In [22]:
B = np.array([[3, 0], [0, 6]])
print('행렬 덧셈:\n', A + B)
print('행렬 곱셈:\n', A * B)

행렬 덧셈:
 [[ 4  2]
 [ 3 10]]
행렬 곱셈:
 [[ 3  0]
 [ 0 24]]


In [24]:
print('A:\n', A)
print('A * 10:\n', A * 10)

A:
 [[1 2]
 [3 4]]
A * 10:
 [[10 20]
 [30 40]]


In [26]:
#브로드캐스트
A = np.array([[1, 2], [3, 4]])
B = np.array([10, 20])
print(A * B)

[[10 40]
 [30 80]]


In [27]:
#원소 접근
X = np.array([[51, 55], [14, 19], [0, 4]])
print('X:\n', X)
print('X[0]:', X[0])
print('X[0][1]:', X[0][1])

X:
 [[51 55]
 [14 19]
 [ 0  4]]
X[0]: [51 55]
X[0][1]: 55


In [28]:
for row in X:
    print(row)

[51 55]
[14 19]
[0 4]


In [30]:
X = X.flatten()
print('X를 1차원 배열로 변환(평탄화):', X)
print('인덱스가 0, 2, 4인 원소 얻기:', X[np.array([0, 2, 4])])

X를 1차원 배열로 변환(평탄화): [51 55 14 19  0  4]
인덱스가 0, 2, 4인 원소 얻기: [51 14  0]


In [32]:
print('X:', X)
print('X에서 15 이상인 값만')
print('여부 출력:', X > 15)
print('원소 값으로 출력:', X[X>15])

X: [51 55 14 19  0  4]
X에서 15 이상인 값만
여부 출력: [ True  True False  True False False]
원소 값으로 출력: [51 55 19]
